name: "Eslint"

on:
  push:
    branches:
      - main
      - javascript

jobs:
  redundant_builds:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
